name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install Boost library
      run: sudo apt-get install -y libboost-all-dev
    - name: Make
      run: make
